version: "3.7"

services:
  postgres:
    container_name: sajic_db
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - sajic_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sajic_db_data:
